menu:
  首页: /
  归档: /archives
  关于我: /about

widgets:
- search
- category
- tag
- tagcloud

excerpt_link: Read More
avatar: /assets/img/avatar/avatar.jpg
baidu_share: true

rss:

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。
comment_provider: wumii

duoshuo:
  short_name: pengloo53

wumii: 
  relateditems: true
  siteprefix: http://www.linux2me.com


#fancybox: false

#google_analytics: false