menu:
  首页: /
  归档: /archives

widgets:
- search
- category
- tag
- tagcloud

excerpt_link: Read More

baidu_share: true

rss:

duoshuo:
  enable: true
  short_name: pengloo53

wumii: 
  enable: true
  siteprefix: http://www.linux2me.com

#comment_provider: facebook
# Facebook comment
#facebook: false
#  appid: 123456789012345
#  comment_count: 5
#  comment_width: 840
#  comment_colorscheme: light

#fancybox: false

#google_analytics: false